package: search_it
version: '5.8.2'
author: Robert Rupf/Norbert Micheel
supportpage: http://www.redaxo.org/de/wiki/index.php?n=R4.Rexsearch


page:
    title: 'translate:title'
    perm: search_it[]
    pjax: false
    icon: rex-icon fa-search
    subpages:
        generate: { title: 'translate:generate', perm: search_it[generate], icon: rex-icon fa-tasks }
        settings:
            title: 'translate:settings'
            perm: search_it[settings]
            icon: rex-icon fa-wrench
            subpages:
                         mode: { title: 'translate:settings_mode' }
                         result: { title: 'translate:settings_result' }
                         origin: { title: 'translate:settings_origin' }

requires:
    redaxo: '^5.2.0'

plugins:
    - plaintext
    - reindex
    - search_highlighter
    - stats
    - documentation
