package: search_it
version: '5.7.8'
author: Friends Of REDAXO/Robert Rupf/Norbert Micheel
supportpage: github.com/FriendsOfREDAXO/search_it


page:
    title: 'translate:title'
    perm: search_it[]
    pjax: false
    icon: rex-icon fa-search
    subpages:
        generate: { title: 'translate:generate', perm: search_it[generate] }
        settings:
            title: 'translate:settings'
            perm: search_it[settings]
            subpages:
                         mode: { title: 'translate:settings_mode' }
                         result: { title: 'translate:settings_result' }
                         origin: { title: 'translate:settings_origin' }
        readme: { title: 'translate:readme' }

system_plugins:
    - plaintext
    - reindex
    - search_highlighter
    - stats
